from __future__ import annotations

TASK_CATEGORY_DAILY = "daily"
TASK_CATEGORY_WEEKLY = "weekly"
TASK_CATEGORY_RISK = "risk"
TASK_CATEGORY_REVIEW = "review"
TASK_CATEGORY_DATA = "data"

TASK_PRIORITY_HIGH = "high"
TASK_PRIORITY_NORMAL = "normal"
TASK_PRIORITY_LOW = "low"

TASK_STATUS_PENDING = "pending"
TASK_STATUS_DONE = "done"
TASK_STATUS_SKIPPED = "skipped"

# Daily tasks
TASK_UPDATE_MARKET_DATA = "update_market_data"
TASK_CHECK_INDICATORS = "check_indicators"
TASK_INPUT_HOLDING_SNAPSHOT = "input_holding_snapshot"
TASK_CHECK_PORTFOLIO_RISK = "check_portfolio_risk"
TASK_GENERATE_STRATEGY_SIGNAL = "generate_strategy_signal"
TASK_REVIEW_STRATEGY_SIGNAL = "review_strategy_signal"
TASK_RECORD_TRADE_LOG = "record_trade_log"
TASK_GENERATE_DAILY_REPORT = "generate_daily_report"
TASK_GENERATE_AI_DAILY_REVIEW = "generate_ai_daily_review"

# Weekly tasks
TASK_GENERATE_WEEKLY_REPORT = "generate_weekly_report"
TASK_GENERATE_AI_WEEKLY_REVIEW = "generate_ai_weekly_review"
TASK_REVIEW_WEEKLY_DISCIPLINE = "review_weekly_discipline"
TASK_CHECK_PORTFOLIO_DEVIATION = "check_portfolio_deviation"

# Risk tasks
TASK_STALE_MARKET_DATA = "stale_market_data"
TASK_MISSING_HOLDING_SNAPSHOT = "missing_holding_snapshot"
TASK_OVERWEIGHT_POSITION = "overweight_position"
TASK_EXCEED_MAX_POSITION = "exceed_max_position"
TASK_WATCH_ONLY_OVERWEIGHT = "watch_only_overweight"
TASK_UNREVIEWED_SIGNAL = "unreviewed_signal"
TASK_NON_RULE_BASED_TRADE = "non_rule_based_trade"

DAILY_TASK_TYPES = {
    TASK_UPDATE_MARKET_DATA,
    TASK_CHECK_INDICATORS,
    TASK_INPUT_HOLDING_SNAPSHOT,
    TASK_CHECK_PORTFOLIO_RISK,
    TASK_GENERATE_STRATEGY_SIGNAL,
    TASK_REVIEW_STRATEGY_SIGNAL,
    TASK_RECORD_TRADE_LOG,
    TASK_GENERATE_DAILY_REPORT,
    TASK_GENERATE_AI_DAILY_REVIEW,
}

WEEKLY_TASK_TYPES = {
    TASK_GENERATE_WEEKLY_REPORT,
    TASK_GENERATE_AI_WEEKLY_REVIEW,
    TASK_REVIEW_WEEKLY_DISCIPLINE,
    TASK_CHECK_PORTFOLIO_DEVIATION,
}

RISK_TASK_TYPES = {
    TASK_STALE_MARKET_DATA,
    TASK_MISSING_HOLDING_SNAPSHOT,
    TASK_OVERWEIGHT_POSITION,
    TASK_EXCEED_MAX_POSITION,
    TASK_WATCH_ONLY_OVERWEIGHT,
    TASK_UNREVIEWED_SIGNAL,
    TASK_NON_RULE_BASED_TRADE,
}

ALL_TASK_TYPES = DAILY_TASK_TYPES | WEEKLY_TASK_TYPES | RISK_TASK_TYPES
